# Generated by Django 4.1.5 on 2023-02-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0008_alter_phone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='release_date',
            field=models.DateField(null=True, verbose_name='%Y-%m-%d'),
        ),
    ]
